### PR TITLE
Minor clean

### PR DESCRIPTION
**Pull request by clementperon**

### CODE REVIEW

**Review by NobuoTsukamoto — APPROVED** [review]

**Comment by NobuoTsukamoto** [comment]
Thank you very much.

**Comment by clementperon** [comment]
@NobuoTsukamoto just for my knowledge did you generate the first Bitbake recipe with ChatGPT or copy from somewhere? There are some lines that are really weird..

**Comment by NobuoTsukamoto** [comment]
I did not create the recipes using chatGPT or GitHub Copilot.
However, I have also created https://github.com/NobuoTsukamoto/meta-tensorflow-lite, but I am not very familiar with Yocto recipes.

If you notice anything strange, I would appreciate it if you could point it out.

**Comment by clementperon** [comment]
> I did not create the recipes using chatGPT or GitHub Copilot. However, I have also created https://github.com/NobuoTsukamoto/meta-tensorflow-lite, but I am not very familiar with Yocto recipes.
> 
> If you notice anything strange, I would appreciate it if you could point it out.

Ok 👌  I'm planning to open other MR to clean the recipe

**Pull request merged**
